### PR TITLE
Fixed error.

### PR DESCRIPTION
**Pull request by OGFris**

### CODE REVIEW

**Comment by beito123** [comment]
What errors did?
no errors on my environment.

**Comment by beito123** [comment]
And if it changes, should changes other functions in Handler also.
I want to make generic programs as possible as I can. 
cuz mcbe will possibly be TCP protocol.

**Comment by OGFris** [comment]
sorry but i was working on my own local version, imma try to download the last one then re upload it with the features i added

**Comment by beito123** [comment]
ok, please try it.
if you still have errors, please tell me :3

**Comment by OGFris** [comment]
btw don't you think you should remove the main package because after all it's just a library, and do the Monitor and the other things in a new repository or maybe as an example like what i did https://github.com/SpecterTeam/go-raknet/blob/master/example/example.go

**Comment by beito123** [comment]
I guess so. ok.
I'll change to such example package. 
thanks.

**Comment by beito123** [comment]
so have you have errors yet?

**Comment by OGFris** [comment]
nope, [my fork](https://github.com/SpecterTeam/go-raknet) doesn't have any erros,

**Comment by beito123** [comment]
ok.

**Pull request closed without merging**
